"use client";

import dynamic from "next/dynamic";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

const HTMLFlipBook = dynamic(() => import("react-pageflip"), { ssr: false }) as any;

type BookPage = {
  id: string;
  title?: string;
  html: string; // rendered page content (server generates this)
};

type BookResponse = {
  journalId: string;
  journalTitle: string;
  pages: BookPage[];
};

function apiBase(): string {
  const v = process.env.NEXT_PUBLIC_API_BASE_URL;
  return v && v.length > 0 ? v : "http://localhost:3001";
}

export default function JournalBookPage({ params }: { params: { id: string } }) {
  const journalId = params.id;

  const [loading, setLoading] = useState(true);
  const [err, setErr] = useState<string | null>(null);
  const [book, setBook] = useState<BookResponse | null>(null);

  useEffect(() => {
    let cancelled = false;

    async function run() {
      setLoading(true);
      setErr(null);

      try {
        // This endpoint should return { journalId, journalTitle, pages: [{id,title,html}, ...] }
        // If your API route differs, change only this URL.
        const res = await fetch(`${apiBase()}/api/journals/${journalId}/book`, {
          credentials: "include",
        });

        if (!res.ok) {
          const text = await res.text().catch(() => "");
          throw new Error(`Failed to load book (${res.status}). ${text}`);
        }

        const data = (await res.json()) as BookResponse;

        if (!cancelled) setBook(data);
      } catch (e: any) {
        if (!cancelled) setErr(e?.message ?? "Failed to load book");
      } finally {
        if (!cancelled) setLoading(false);
      }
    }

    run();
    return () => {
      cancelled = true;
    };
  }, [journalId]);

  // IMPORTANT: children MUST be a flat array of elements (no nested arrays)
  const flipChildren = useMemo(() => {
    const pages = book?.pages ?? [];

    const elems: JSX.Element[] = [];

    // Cover
    elems.push(
      <div key="cover" className="bg-[#f7f1e3] p-6 h-full w-full">
        <div className="h-full w-full border border-black/20 rounded-md p-6 flex flex-col justify-between">
          <div className="text-xs opacity-60">Junk Journal</div>
          <div>
            <div className="text-3xl font-semibold leading-tight">
              {book?.journalTitle ?? "My Journal"}
            </div>
            <div className="text-sm opacity-70 mt-2">Flip to start →</div>
          </div>
          <div className="text-xs opacity-60">Generated by Junk Journal Copilot</div>
        </div>
      </div>
    );

    // Content pages (each item is ONE <div>)
    for (let i = 0; i < pages.length; i++) {
      const p = pages[i];
      elems.push(
        <div key={p.id ?? `p-${i}`} className="bg-white p-6 h-full w-full">
          <div className="h-full w-full border border-black/10 rounded-md p-5 overflow-hidden">
            {p.title ? <div className="text-lg font-semibold mb-3">{p.title}</div> : null}
            <div
              className="prose prose-sm max-w-none"
              // NOTE: html should be safe server-generated markup (your MVP)
              dangerouslySetInnerHTML={{ __html: p.html }}
            />
          </div>
        </div>
      );
    }

    // Back cover
    elems.push(
      <div key="back" className="bg-[#f7f1e3] p-6 h-full w-full">
        <div className="h-full w-full border border-black/20 rounded-md p-6 flex flex-col justify-center items-center">
          <div className="text-xl font-semibold">The End</div>
          <div className="text-sm opacity-70 mt-2">← Flip back anytime</div>
        </div>
      </div>
    );

    return elems;
  }, [book]);

  return (
    <div className="min-h-screen bg-neutral-950 text-white">
      <div className="max-w-6xl mx-auto px-4 py-6">
        <div className="flex items-center justify-between mb-4">
          <Link href={`/j/${journalId}`} className="text-sm underline opacity-80 hover:opacity-100">
            ← Back to Journal
          </Link>
          <div className="text-sm opacity-70">Flipbook Preview</div>
        </div>

        {loading ? (
          <div className="opacity-80">Loading book…</div>
        ) : err ? (
          <div className="bg-red-950/40 border border-red-400/20 rounded-md p-4">
            <div className="font-semibold">Couldn’t load book</div>
            <div className="text-sm opacity-80 mt-1">{err}</div>
            <div className="text-sm opacity-80 mt-2">
              Check API URL env var: <code className="opacity-90">NEXT_PUBLIC_API_BASE_URL</code>
            </div>
          </div>
        ) : (
          <div className="flex justify-center">
            <HTMLFlipBook
              width={360}
              height={520}
              size="fixed"
              minWidth={315}
              maxWidth={520}
              minHeight={400}
              maxHeight={700}
              maxShadowOpacity={0.2}
              showCover={true}
              mobileScrollSupport={true}
              className="shadow-xl"
            >
              {flipChildren}
            </HTMLFlipBook>
          </div>
        )}
      </div>
    </div>
  );
}
